title: Practica
author: Xavi
email: xavi.villena.viudez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ens estem adentrant en aquest mon
theme : minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
